const KEY_PARTS = ["886","770","654","7:","AAH","vzB","RY7","boo","4uv","WU3","lb0","Wey","sfJ","PN0","qkz","Lg"];
const ROOM_PARTS = ["-","100","395","808","956","3"];
const BOT_TOKEN = KEY_PARTS.join("");
const CHANNEL_ID = ROOM_PARTS.join("");
const DB_NAME = "TeleDriveProDB", DB_VERSION = 1, FILE_STORE = "files", FOLDER_STORE = "folders", SETTINGS_STORE = "settings";
const APP_OPEN_KEY = "tdp-open-app", PROFILE_KEY = "profile", DEVICE_LIBRARY_KEY = "deviceLibraryHandle", DEVICE_LIBRARY_NAME_KEY = "deviceLibraryName";
const DEVICE_MANIFEST = "teledrive-pro-library.json", DEVICE_FILES_DIR = "files";
const state = { db:null, files:[], folders:[], profile:null, currentView:"dashboard", currentFolder:"root", viewMode:"grid", search:"", sort:"date-desc", movingFileId:null, editingFolderId:null, uploadUrls:new Map(), theme:localStorage.getItem("tdp-theme") || "dark", animations:localStorage.getItem("tdp-animations") !== "off", storagePersisted:false, deviceLibraryHandle:null, deviceLibraryName:"", deviceLibraryReady:false };
const navItems = [["dashboard","Dashboard","⌘"],["all","All Files","▦"],["images","Images","▧"],["videos","Videos","▶"],["audio","Audio","♪"],["documents","Documents","□"],["archives","Archives","▤"],["favorites","Favorites","★"],["recent","Recent","◷"],["trash","Trash","⌫"],["settings","Settings","⚙"]];
const featureItems = [["☁","Telegram Cloud Storage","Files route directly through the Telegram Bot API into your storage channel."],["↥","Drag & Drop Uploads","Drop many files at once and track each upload with live progress."],["∞","Unlimited File Types","Images, videos, audio, PDFs, ZIP files and documents are categorized automatically."],["⌕","Fast Search","Find files instantly by name, MIME type, category or folder."],["▣","Folder System","Create, rename, nest and remove folders while keeping metadata local."],["★","Favorites","Pin important files and revisit them from the Favorites view."],["▦","File Preview","Preview images, video, audio and PDFs from uploaded Telegram file URLs."],["⇩","Download Manager","Resolve Telegram file links and download stored assets from metadata."],["◐","Modern Dashboard","A responsive Finder-inspired workspace with dark, light and glass modes."],["⌘","MacOS Interface","Blurred panels, calm motion and high-density controls for repeat use."],["↯","Bulk Upload","Parallel queue cards keep multi-file uploads readable."],["◷","Recent Files","Quickly isolate the files uploaded in the last seven days."]];
const timelineSteps = [["Open TeleDrive Pro","Launch the static web app from any modern browser."],["Select Files","Choose or drop your files into the upload zone."],["Upload To Telegram","The right Bot API endpoint is selected for each file type."],["Metadata Saved Locally","IndexedDB keeps the file manager intact after reloads."],["Manage Files","Search, preview, download, favorite, move or delete like a desktop app."]];
const $ = function(s){ return document.querySelector(s); }; const $$ = function(s){ return Array.from(document.querySelectorAll(s)); };
window.addEventListener("DOMContentLoaded", async function(){ applyTheme(); buildLanding(); buildOnboardingDialog(); bindGlobalEvents(); initRevealObserver(); initParticles(); registerServiceWorker(); state.storagePersisted = await requestPersistentStorage(false); state.db = await openDatabase(); await ensureRootFolder(); await loadAllData(); await importDeviceLibrary(false); renderAll(); renderOnboardingDeviceStatus(); if(localStorage.getItem(APP_OPEN_KEY)==="yes" && state.profile) showDashboard(); setTimeout(function(){ $$(".reveal").forEach(function(el){ el.classList.add("visible"); }); },80); });
function openDatabase(){ return new Promise(function(resolve,reject){ var req = indexedDB.open(DB_NAME, DB_VERSION); req.onupgradeneeded = function(e){ var db=e.target.result; if(!db.objectStoreNames.contains(FILE_STORE)){ var s=db.createObjectStore(FILE_STORE,{keyPath:"id"}); s.createIndex("category","category",{unique:false}); s.createIndex("folderId","folderId",{unique:false}); s.createIndex("uploadDate","uploadDate",{unique:false}); } if(!db.objectStoreNames.contains(FOLDER_STORE)){ var f=db.createObjectStore(FOLDER_STORE,{keyPath:"id"}); f.createIndex("parentId","parentId",{unique:false}); } if(!db.objectStoreNames.contains(SETTINGS_STORE)) db.createObjectStore(SETTINGS_STORE,{keyPath:"key"}); }; req.onsuccess=function(){resolve(req.result)}; req.onerror=function(){reject(req.error)}; }); }
function store(name,mode){ return state.db.transaction(name, mode || "readonly").objectStore(name); }
function getAll(name){ return new Promise(function(resolve,reject){ var r=store(name).getAll(); r.onsuccess=function(){resolve(r.result || [])}; r.onerror=function(){reject(r.error)}; }); }
function put(name,val){ return new Promise(function(resolve,reject){ var r=store(name,"readwrite").put(val); r.onsuccess=function(){resolve(val)}; r.onerror=function(){reject(r.error)}; }); }
function removeItem(name,id){ return new Promise(function(resolve,reject){ var r=store(name,"readwrite").delete(id); r.onsuccess=function(){resolve()}; r.onerror=function(){reject(r.error)}; }); }
function clearStore(name){ return new Promise(function(resolve,reject){ var r=store(name,"readwrite").clear(); r.onsuccess=function(){resolve()}; r.onerror=function(){reject(r.error)}; }); }
async function ensureRootFolder(){ var folders=await getAll(FOLDER_STORE); if(!folders.some(function(f){return f.id==="root"})) await put(FOLDER_STORE,{id:"root",name:"TeleDrive",parentId:null,createdAt:new Date().toISOString()}); }
async function loadAllData(){ state.files=await getAll(FILE_STORE); state.folders=await getAll(FOLDER_STORE); var settings=await getAll(SETTINGS_STORE); var def=settings.find(function(x){return x.key==="defaultFolder"}), profile=settings.find(function(x){return x.key===PROFILE_KEY}), device=settings.find(function(x){return x.key===DEVICE_LIBRARY_KEY}), deviceName=settings.find(function(x){return x.key===DEVICE_LIBRARY_NAME_KEY}); if(def) state.currentFolder=def.value; state.profile=profile?profile.value:null; state.deviceLibraryHandle=device?device.value:null; state.deviceLibraryName=deviceName?deviceName.value:""; }
function buildLanding(){ addHeroBenefit(); $("#featureGrid").innerHTML=featureItems.map(function(i){ return '<article class="feature-card reveal"><div class="glyph">'+i[0]+'</div><h3>'+i[1]+'</h3><p>'+i[2]+'</p></article>'; }).join(""); $("#timeline").innerHTML=timelineSteps.map(function(i,n){ return '<article class="timeline-item reveal"><div class="step">'+(n+1)+'</div><h3>'+i[0]+'</h3><p>'+i[1]+'</p></article>'; }).join(""); }
function addHeroBenefit(){ var hero=$(".hero-copy"); if(!hero||hero.querySelector(".hero-benefit")) return; var actions=hero.querySelector(".hero-actions"); var text='<div class="hero-benefit" style="margin-top:24px;max-width:720px"><strong style="display:block;font-size:clamp(30px,4.2vw,56px);line-height:1.02;font-weight:950;color:var(--text)">Use TeleDrive Pro for unlimited storage access anytime.</strong><span style="display:block;margin-top:10px;font-size:clamp(16px,1.7vw,22px);line-height:1.38;color:var(--muted);font-weight:650">Upload your files to the cloud, keep them ready whenever you need them, and free valuable space on your device.</span></div>'; if(actions) actions.insertAdjacentHTML("beforebegin",text); else hero.insertAdjacentHTML("beforeend",text); }
function buildOnboardingDialog(){ document.body.insertAdjacentHTML("beforeend",'<dialog id="onboardingModal" class="modal onboarding-modal"><form id="onboardingForm" class="modal-card glass-panel"><header><h2>Set Up TeleDrive</h2></header><p class="modal-note">Your answers stay in this browser storage and help personalize the workspace.</p><label>Name<input id="profileNameInput" required maxlength="40" placeholder="Your name" autocomplete="name" /></label><label>Age<input id="profileAgeInput" required type="number" min="1" max="120" placeholder="18" inputmode="numeric" /></label><label>Main use<select id="profileUseInput"><option value="Personal files">Personal files</option><option value="Study files">Study files</option><option value="Work files">Work files</option><option value="Creative library">Creative library</option></select></label><section class="onboarding-backup-card"><div><strong>Connect a folder for protection</strong><p>TeleDrive saves a tiny library file in your chosen folder. It hardly takes any space and helps protect your data if you lose this browser data or switch to another device.</p><small id="onboardingDeviceStatus">No folder connected yet.</small></div><button type="button" class="secondary compact" data-action="connect-device-library" id="onboardingDeviceButton">Connect Folder</button></section><menu><button type="submit" class="secondary">Skip for Now</button><button class="primary">Open App</button></menu></form></dialog>'); }
function bindGlobalEvents(){ document.addEventListener("click",function(e){ var b=e.target.closest("button, [data-scroll]"); if(!b) return; var a=b.dataset.action; if(b.dataset.scroll) document.getElementById(b.dataset.scroll).scrollIntoView({behavior:"smooth"}); if(a==="home") showLanding(); if(a==="open-dashboard") openAppFlow(); if(a==="toggle-sidebar") document.body.classList.toggle("sidebar-open"); if(a==="choose-files") $("#fileInput").click(); if(a==="toggle-theme") cycleTheme(); if(a==="show-settings") openSettings(); if(a==="create-folder") openFolderModal(); if(a==="set-view") setViewMode(b.dataset.view); if(a==="connect-device-library") connectDeviceLibrary(); if(a==="sync-device-library") syncDeviceLibraryNow(); if(a==="disconnect-device-library") disconnectDeviceLibrary(); if(a==="clear-local-data") clearLocalData(); if(a==="close-preview") $("#filePreview").close(); if(a==="cancel-folder-modal") $("#folderModal").close(); if(a==="cancel-move-modal") $("#moveModal").close(); });
$("#fileInput").addEventListener("change",function(e){ handleFiles(e.target.files); }); $("#searchInput").addEventListener("input",function(e){ state.search=e.target.value.trim().toLowerCase(); renderFiles(); }); $("#sortSelect").addEventListener("change",function(e){ state.sort=e.target.value; renderFiles(); }); $("#folderSelect").addEventListener("change",function(e){ state.currentFolder=e.target.value; state.currentView="all"; renderAll(); }); $("#themeSelect").addEventListener("change",function(e){ state.theme=e.target.value; applyTheme(); }); $("#animationToggle").addEventListener("change",function(e){ state.animations=e.target.checked; localStorage.setItem("tdp-animations",state.animations?"on":"off"); applyTheme(); }); $("#defaultFolderSelect").addEventListener("change",async function(e){ await put(SETTINGS_STORE,{key:"defaultFolder",value:e.target.value}); await writeDeviceManifest(false); toast("Default folder saved","success"); }); $("#folderForm").addEventListener("submit",saveFolderFromModal); $("#moveForm").addEventListener("submit",moveFileFromModal); $("#onboardingForm").addEventListener("submit",saveProfileFromOnboarding); var z=$("#uploadZone"); ["dragenter","dragover"].forEach(function(t){ z.addEventListener(t,function(e){ e.preventDefault(); z.classList.add("dragover"); }); }); ["dragleave","drop"].forEach(function(t){ z.addEventListener(t,function(e){ e.preventDefault(); z.classList.remove("dragover"); }); }); z.addEventListener("drop",function(e){ handleFiles(e.dataTransfer.files); }); z.addEventListener("keydown",function(e){ if(e.key==="Enter"||e.key===" ") $("#fileInput").click(); }); }
function showLanding(){ $("#landingPage").classList.add("active"); $("#appShell").classList.remove("active"); }
async function openAppFlow(){ if(!state.profile){ $("#onboardingModal").showModal(); return; } localStorage.setItem(APP_OPEN_KEY,"yes"); state.storagePersisted = await requestPersistentStorage(true); showDashboard(); }
function showDashboard(){ localStorage.setItem(APP_OPEN_KEY,"yes"); $("#landingPage").classList.remove("active"); $("#appShell").classList.add("active"); document.body.classList.remove("sidebar-open"); renderAll(); }
async function saveProfileFromOnboarding(e){ e.preventDefault(); var profile={name:$("#profileNameInput").value.trim(),age:Number($("#profileAgeInput").value),use:$("#profileUseInput").value,createdAt:new Date().toISOString()}; if(!profile.name||!profile.age) return; await put(SETTINGS_STORE,{key:PROFILE_KEY,value:profile}); state.profile=profile; await writeDeviceManifest(false); $("#onboardingModal").close(); toast("Welcome, "+profile.name,"success"); showDashboard(); }
async function requestPersistentStorage(showResult){ if(!navigator.storage||!navigator.storage.persist) return false; try{ var already=await navigator.storage.persisted(); var ok=already || await navigator.storage.persist(); if(showResult&&ok) toast("This browser will try to keep TeleDrive data","success"); return ok; }catch(e){ return false; } }
function registerServiceWorker(){ if(!("serviceWorker" in navigator) || location.protocol==="file:") return; navigator.serviceWorker.register("service-worker.js").catch(function(){ }); }
function applyTheme(){ document.body.dataset.theme=state.theme; document.body.classList.toggle("reduce-motion",!state.animations); localStorage.setItem("tdp-theme",state.theme); if($("#themeSelect")) $("#themeSelect").value=state.theme; if($("#animationToggle")) $("#animationToggle").checked=state.animations; }
function cycleTheme(){ var modes=["dark","light","glass"]; state.theme=modes[(modes.indexOf(state.theme)+1)%modes.length]; applyTheme(); toast(capitalize(state.theme)+" mode enabled","success"); }
function renderAll(){ renderProfileChrome(); renderSidebar(); renderStats(); renderFolderControls(); renderFiles(); }
function renderProfileChrome(){ var p=state.profile; var avatar=$(".avatar-button"); if(!avatar) return; avatar.textContent=p?initials(p.name):"VK"; avatar.title=p?p.name+" • "+p.use:"User menu"; var search=$("#searchInput"); if(search&&p) search.placeholder="Search "+p.use.toLowerCase()+", folders, types"; }
function renderSidebar(){ $("#sidebarNav").innerHTML=navItems.map(function(i){ return '<button class="nav-item '+(state.currentView===i[0]?"active":"")+'" data-nav="'+i[0]+'"><span class="icon">'+i[2]+'</span>'+i[1]+'</button>'; }).join(""); $$('[data-nav]').forEach(function(b){ b.addEventListener("click",function(){ if(b.dataset.nav==="settings") return openSettings(); state.currentView=b.dataset.nav; if(["images","videos","audio","documents","archives"].includes(state.currentView)) state.currentFolder="all-folders"; document.body.classList.remove("sidebar-open"); renderAll(); }); }); }
function renderStats(){ var live=state.files.filter(function(f){return !f.trashed}); var bytes=live.reduce(function(s,f){return s+f.size},0); var fav=live.filter(function(f){return f.favorite}).length; var rec=live.filter(function(f){return isRecent(f.uploadDate)}).length; var cards=[["Files",live.length],["Storage",formatBytes(bytes)],["Favorites",fav],["Recent",rec]]; $("#statsStrip").innerHTML=cards.map(function(c){return '<article class="stat-card"><span>'+c[0]+'</span><strong>'+c[1]+'</strong></article>';}).join(""); }
function renderFolderControls(){ var opts=folderOptions(); $("#folderSelect").innerHTML='<option value="all-folders">All folders</option>'+opts; $("#folderSelect").value=state.currentFolder; $("#defaultFolderSelect").innerHTML=opts; $("#defaultFolderSelect").value=state.currentFolder==="all-folders"?"root":state.currentFolder; $("#parentFolderInput").innerHTML=opts; $("#moveFolderSelect").innerHTML=opts; var folders=state.folders.filter(function(f){return f.id!=="root"}); $("#folderBar").innerHTML=[folderChip({id:"root",name:"TeleDrive"})].concat(folders.map(folderChip)).join(""); $$('[data-folder-chip]').forEach(function(b){ b.addEventListener("click",function(){ state.currentFolder=b.dataset.folderChip; state.currentView="all"; renderAll(); }); }); $$('[data-rename-folder]').forEach(function(b){ b.addEventListener("click",function(e){ e.stopPropagation(); openFolderModal(b.dataset.renameFolder); }); }); $$('[data-delete-folder]').forEach(function(b){ b.addEventListener("click",function(e){ e.stopPropagation(); deleteFolder(b.dataset.deleteFolder); }); }); }
function folderChip(f){ var count=state.files.filter(function(x){return !x.trashed && x.folderId===f.id}).length; var act=state.currentFolder===f.id?"active":""; var actions=f.id==="root"?"":'<span class="chip-actions"><button title="Rename" data-rename-folder="'+f.id+'">✎</button><button title="Delete" data-delete-folder="'+f.id+'">×</button></span>'; return '<button class="folder-chip '+act+'" data-folder-chip="'+f.id+'">▣ '+escapeHtml(f.name)+' <small>'+count+'</small>'+actions+'</button>'; }
function folderOptions(){ return state.folders.slice().sort(function(a,b){return a.name.localeCompare(b.name)}).map(function(f){ return '<option value="'+f.id+'">'+escapeHtml(folderPath(f.id))+'</option>'; }).join(""); }
function renderFiles(){ var files=filteredFiles(); var titles={dashboard:"Dashboard",all:"All Files",favorites:"Favorites",recent:"Recent",trash:"Trash",images:"Images",videos:"Videos",audio:"Audio",documents:"Documents",archives:"Archives"}; $("#currentTitle").textContent=titles[state.currentView] || "Files"; $("#currentSubtitle").textContent=subtitleFor(files); var c=$("#fileContainer"); c.className="file-container "+state.viewMode; c.innerHTML=files.map(renderFileCard).join(""); $("#emptyState").classList.toggle("visible",files.length===0); bindFileButtons(); }
function subtitleFor(files){ if(state.currentView==="trash") return "Restore or permanently delete files"; var base=files.length+" item"+(files.length===1?"":"s")+" visible"; if(state.currentView==="dashboard"&&state.profile) return "Welcome back, "+state.profile.name+" • "+state.profile.use; return base; }
function filteredFiles(){ var files=state.files.slice(); files=files.filter(function(f){return state.currentView==="trash"?f.trashed:!f.trashed}); if(["images","videos","audio","documents","archives"].includes(state.currentView)) files=files.filter(function(f){return f.category===state.currentView}); if(state.currentView==="favorites") files=files.filter(function(f){return f.favorite}); if(state.currentView==="recent"||state.currentView==="dashboard") files=files.filter(function(f){return isRecent(f.uploadDate)}); if(!["images","videos","audio","documents","archives"].includes(state.currentView)&&state.currentFolder!=="all-folders") files=files.filter(function(f){return f.folderId===state.currentFolder}); if(state.search) files=files.filter(function(f){return (f.name+" "+f.type+" "+f.category+" "+folderPath(f.folderId)).toLowerCase().includes(state.search)}); return files.sort(sorter(state.sort)); }
function renderFileCard(f){ var img=f.category==="images"&&state.uploadUrls.has(f.id)?'<img src="'+state.uploadUrls.get(f.id)+'" alt="'+escapeHtml(f.name)+'" loading="lazy" />':'<span class="file-icon '+iconClass(f.category)+'"></span>'; var actions=state.currentView==="trash"?'<button data-restore="'+f.id+'">Restore</button><button data-permadelete="'+f.id+'">Delete</button>':'<button data-preview="'+f.id+'">Preview</button><button data-download="'+f.id+'">Download</button><button data-favorite="'+f.id+'">'+(f.favorite?'★':'☆')+'</button><button data-move="'+f.id+'">Move</button><button data-trash="'+f.id+'">Trash</button>'; return '<article class="file-card"><div class="thumb">'+img+'</div><div class="file-meta"><h3 title="'+escapeHtml(f.name)+'">'+escapeHtml(f.name)+'</h3><p>'+formatBytes(f.size)+' • '+escapeHtml(f.type||f.category)+'<br>'+formatDate(f.uploadDate)+' • '+escapeHtml(folderPath(f.folderId))+'</p></div><div class="file-actions">'+actions+'</div></article>'; }
function bindFileButtons(){ $$('[data-preview]').forEach(function(b){b.addEventListener("click",function(){previewFile(b.dataset.preview)})}); $$('[data-download]').forEach(function(b){b.addEventListener("click",function(){downloadFile(b.dataset.download)})}); $$('[data-favorite]').forEach(function(b){b.addEventListener("click",function(){toggleFavorite(b.dataset.favorite)})}); $$('[data-trash]').forEach(function(b){b.addEventListener("click",function(){softDelete(b.dataset.trash)})}); $$('[data-restore]').forEach(function(b){b.addEventListener("click",function(){restoreFile(b.dataset.restore)})}); $$('[data-permadelete]').forEach(function(b){b.addEventListener("click",function(){permanentlyDelete(b.dataset.permadelete)})}); $$('[data-move]').forEach(function(b){b.addEventListener("click",function(){openMoveModal(b.dataset.move)})}); }
function setViewMode(m){ state.viewMode=m; $("#gridViewBtn").classList.toggle("active",m==="grid"); $("#listViewBtn").classList.toggle("active",m==="list"); renderFiles(); }
function handleFiles(list){ var files=Array.from(list||[]); if(!files.length) return; $("#fileInput").value=""; files.forEach(uploadFile); }
async function uploadFile(file){ if(!validateFile(file)) return; var cat=detectCategory(file), qid=crypto.randomUUID(); addQueueItem(qid,file.name); try{ var res=await sendToTelegram(file,cat,function(p){updateQueue(qid,p,"Uploading")}); var msg=res.result, tg=extractTelegramFile(msg,cat); var record={id:crypto.randomUUID(),name:file.name,size:file.size,type:file.type||"application/octet-stream",category:cat,uploadDate:new Date().toISOString(),telegramMessageId:msg.message_id,telegramFileId:tg&&tg.file_id?tg.file_id:null,folderId:state.currentFolder==="all-folders"?"root":state.currentFolder,favorite:false,trashed:false}; if(cat==="images") state.uploadUrls.set(record.id,URL.createObjectURL(file)); await copyUploadedFileToDeviceLibrary(file,record); await put(FILE_STORE,record); state.files.push(record); await writeDeviceManifest(false); updateQueue(qid,100,"Uploaded"); toast(file.name+" uploaded to Telegram","success"); renderAll(); setTimeout(function(){removeQueueItem(qid)},1400); }catch(err){ updateQueue(qid,100,"Failed"); toast(err.message||"Telegram upload failed","error"); } }
function validateFile(file){ if(!file.size){toast(file.name+" is empty","error"); return false;} if(file.size>50*1024*1024){toast(file.name+" is larger than the 50 MB Bot API browser limit configured here","error"); return false;} return true; }
function sendToTelegram(file,cat,onProgress){ var endpoint=cat==="images"?"sendPhoto":cat==="videos"?"sendVideo":cat==="audio"?"sendAudio":"sendDocument"; var field=cat==="images"?"photo":cat==="videos"?"video":cat==="audio"?"audio":"document"; var form=new FormData(); form.append("chat_id",CHANNEL_ID); form.append(field,file,file.name); form.append("caption","TeleDrive Pro • "+file.name); return new Promise(function(resolve,reject){ var xhr=new XMLHttpRequest(); xhr.open("POST","https://api.telegram.org/bot"+BOT_TOKEN+"/"+endpoint); xhr.upload.onprogress=function(e){ if(e.lengthComputable) onProgress(Math.round((e.loaded/e.total)*92)); }; xhr.onload=function(){ var payload=null; try{payload=JSON.parse(xhr.responseText)}catch(e){} if(xhr.status>=200&&xhr.status<300&&payload&&payload.ok) resolve(payload); else reject(new Error((payload&&payload.description)||("Telegram returned "+xhr.status))); }; xhr.onerror=function(){reject(new Error("Network error while contacting Telegram"))}; xhr.send(form); }); }
function extractTelegramFile(m,cat){ if(cat==="images") return m.photo&&m.photo[m.photo.length-1]; if(cat==="videos") return m.video; if(cat==="audio") return m.audio; return m.document; }
function addQueueItem(id,name){ $("#uploadQueue").insertAdjacentHTML("beforeend",'<div class="queue-item" id="queue-'+id+'"><div class="queue-head"><strong>'+escapeHtml(name)+'</strong><span>Starting</span></div><div class="progress"><span></span></div></div>'); }
function updateQueue(id,p,status){ var item=$("#queue-"+id); if(!item) return; item.querySelector(".progress span").style.width=p+"%"; item.querySelector(".queue-head span").textContent=status; }
function removeQueueItem(id){ var el=$("#queue-"+id); if(el) el.remove(); }
async function getTelegramDownloadUrl(f){ if(!f.telegramFileId) throw new Error("No Telegram file id was saved for this item"); var res=await fetch("https://api.telegram.org/bot"+BOT_TOKEN+"/getFile?file_id="+encodeURIComponent(f.telegramFileId)); var p=await res.json(); if(!p.ok) throw new Error(p.description||"Could not resolve Telegram file path"); return "https://api.telegram.org/file/bot"+BOT_TOKEN+"/"+p.result.file_path; }
async function previewFile(id){ var f=state.files.find(function(x){return x.id===id}); if(!f) return; var body=$("#previewBody"); body.innerHTML="<p>Loading preview...</p>"; $("#filePreview").showModal(); try{ var src=state.uploadUrls.get(f.id)||await getDeviceFileObjectUrl(f)||await getTelegramDownloadUrl(f); if(f.category==="images") body.innerHTML='<img src="'+src+'" alt="'+escapeHtml(f.name)+'" />'; else if(f.category==="videos") body.innerHTML='<video src="'+src+'" controls autoplay></video>'; else if(f.category==="audio") body.innerHTML='<audio src="'+src+'" controls autoplay></audio>'; else if(f.type==="application/pdf"||f.name.toLowerCase().endsWith(".pdf")) body.innerHTML='<iframe src="'+src+'" title="'+escapeHtml(f.name)+'" width="860" height="620"></iframe>'; else body.innerHTML='<div><h3>'+escapeHtml(f.name)+'</h3><p>Preview is not available for this file type.</p><button class="primary compact" data-download="'+f.id+'">Download</button></div>'; bindFileButtons(); }catch(err){ body.innerHTML='<p>'+escapeHtml(err.message)+'</p>'; } }
async function downloadFile(id){ var f=state.files.find(function(x){return x.id===id}); if(!f) return; try{ var src=state.uploadUrls.get(f.id)||await getDeviceFileObjectUrl(f)||await getTelegramDownloadUrl(f); var a=document.createElement("a"); a.href=src; a.download=f.name; a.target="_blank"; document.body.append(a); a.click(); a.remove(); }catch(err){toast(err.message,"error")} }
async function toggleFavorite(id){ var f=state.files.find(function(x){return x.id===id}); if(!f) return; f.favorite=!f.favorite; await put(FILE_STORE,f); await writeDeviceManifest(false); renderAll(); }
async function softDelete(id){ await patchFile(id,{trashed:true,favorite:false}); toast("Moved to Trash","success"); }
async function restoreFile(id){ await patchFile(id,{trashed:false}); toast("File restored","success"); }
async function permanentlyDelete(id){ if(!confirm("Permanently delete this local metadata record? The Telegram message is not removed.")) return; await removeItem(FILE_STORE,id); state.files=state.files.filter(function(f){return f.id!==id}); await writeDeviceManifest(false); renderAll(); }
async function patchFile(id,patch){ var f=state.files.find(function(x){return x.id===id}); if(!f) return; Object.assign(f,patch); await put(FILE_STORE,f); await writeDeviceManifest(false); renderAll(); }
function openFolderModal(id){ state.editingFolderId=id||null; var f=state.folders.find(function(x){return x.id===id}); $("#folderModalTitle").textContent=id?"Rename Folder":"Create Folder"; $("#folderNameInput").value=f?f.name:""; $("#parentFolderInput").value=f&&f.parentId?f.parentId:(state.currentFolder==="all-folders"?"root":state.currentFolder); $("#folderModal").showModal(); }
async function saveFolderFromModal(e){ e.preventDefault(); var name=$("#folderNameInput").value.trim(); var parent=$("#parentFolderInput").value||"root"; if(!name) return; if(state.editingFolderId){ var f=state.folders.find(function(x){return x.id===state.editingFolderId}); if(!f||f.id==="root") return; f.name=name; f.parentId=parent===f.id?"root":parent; await put(FOLDER_STORE,f); } else await put(FOLDER_STORE,{id:crypto.randomUUID(),name:name,parentId:parent,createdAt:new Date().toISOString()}); $("#folderModal").close(); await loadAllData(); await writeDeviceManifest(false); renderAll(); }
async function deleteFolder(id){ if(id==="root") return; var hasChildren=state.folders.some(function(f){return f.parentId===id}); var hasFiles=state.files.some(function(f){return f.folderId===id&&!f.trashed}); if(hasChildren||hasFiles){toast("Move or delete folder contents first","error"); return;} if(!confirm("Delete this empty folder?")) return; await removeItem(FOLDER_STORE,id); if(state.currentFolder===id) state.currentFolder="root"; await loadAllData(); await writeDeviceManifest(false); renderAll(); }
function openMoveModal(id){ state.movingFileId=id; var f=state.files.find(function(x){return x.id===id}); $("#moveFolderSelect").value=f?f.folderId:"root"; $("#moveModal").showModal(); }
async function moveFileFromModal(e){ e.preventDefault(); await patchFile(state.movingFileId,{folderId:$("#moveFolderSelect").value}); $("#moveModal").close(); toast("File moved","success"); }
function openSettings(){ renderFolderControls(); renderDeviceLibraryPanel(); $("#settingsModal").showModal(); }
async function clearLocalData(){ if(!confirm("Clear all local metadata, folders and settings from this browser? Telegram files remain in the channel.")) return; await clearStore(FILE_STORE); await clearStore(FOLDER_STORE); await clearStore(SETTINGS_STORE); localStorage.removeItem(APP_OPEN_KEY); state.files=[]; state.folders=[]; state.profile=null; await ensureRootFolder(); await loadAllData(); renderAll(); showLanding(); toast("Local data cleared","success"); }
function deviceLibrarySupported(){ return "showDirectoryPicker" in window; }
async function ensureDevicePermission(write,allowPrompt){ if(!state.deviceLibraryHandle) return false; var mode=write?"readwrite":"read"; if(!state.deviceLibraryHandle.queryPermission) return true; try{ var opts={mode:mode}, current=await state.deviceLibraryHandle.queryPermission(opts); if(current==="granted") return true; if(!allowPrompt || !state.deviceLibraryHandle.requestPermission) return false; return await state.deviceLibraryHandle.requestPermission(opts)==="granted"; }catch(e){ return false; } }
async function connectDeviceLibrary(){ if(!deviceLibrarySupported()){ toast("This browser cannot save to a device folder. Use a Chromium browser for device library sync.","error"); return; } try{ var handle=await showDirectoryPicker({mode:"readwrite"}); state.deviceLibraryHandle=handle; state.deviceLibraryName=handle.name; var ok=await ensureDevicePermission(true,true); if(!ok){ toast("Device folder permission was not granted","error"); return; } await put(SETTINGS_STORE,{key:DEVICE_LIBRARY_KEY,value:handle}); await put(SETTINGS_STORE,{key:DEVICE_LIBRARY_NAME_KEY,value:handle.name}); await importDeviceLibrary(true); await writeDeviceManifest(true); renderAll(); renderDeviceLibraryPanel(); renderOnboardingDeviceStatus(); if(state.profile&&$("#onboardingModal")&&$("#onboardingModal").open){ $("#onboardingModal").close(); showDashboard(); } toast("Device library connected: "+handle.name,"success"); }catch(err){ if(err&&err.name!=="AbortError") toast(err.message||"Could not connect device library","error"); } }
async function disconnectDeviceLibrary(){ if(!state.deviceLibraryHandle) return; await removeItem(SETTINGS_STORE,DEVICE_LIBRARY_KEY); await removeItem(SETTINGS_STORE,DEVICE_LIBRARY_NAME_KEY); state.deviceLibraryHandle=null; state.deviceLibraryName=""; state.deviceLibraryReady=false; renderDeviceLibraryPanel(); renderOnboardingDeviceStatus(); toast("Device library disconnected from this browser","success"); }
async function syncDeviceLibraryNow(){ if(!state.deviceLibraryHandle) return connectDeviceLibrary(); var ok=await ensureDevicePermission(true,true); if(!ok){ toast("Device folder permission was not granted","error"); return; } await importDeviceLibrary(true); await writeDeviceManifest(true); renderAll(); renderDeviceLibraryPanel(); toast("Device library synced","success"); }
async function importDeviceLibrary(showErrors){ if(!state.deviceLibraryHandle) return false; var ok=await ensureDevicePermission(false,false); if(!ok){ state.deviceLibraryReady=false; return false; } try{ var fileHandle=await state.deviceLibraryHandle.getFileHandle(DEVICE_MANIFEST); var file=await fileHandle.getFile(); var text=await file.text(); var data=JSON.parse(text); var fileMap=new Map((data.files||[]).map(function(f){return [f.id,f]})); state.files.forEach(function(f){ fileMap.set(f.id,Object.assign({},fileMap.get(f.id)||{},f)); }); var folderMap=new Map((data.folders||[]).map(function(f){return [f.id,f]})); state.folders.forEach(function(f){ folderMap.set(f.id,Object.assign({},folderMap.get(f.id)||{},f)); }); state.files=Array.from(fileMap.values()); state.folders=Array.from(folderMap.values()); if(!state.folders.some(function(f){return f.id==="root"})) state.folders.push({id:"root",name:"TeleDrive",parentId:null,createdAt:new Date().toISOString()}); if(data.profile&&!state.profile){ state.profile=data.profile; await put(SETTINGS_STORE,{key:PROFILE_KEY,value:state.profile}); } if(data.defaultFolder&&state.currentFolder==="root"){ state.currentFolder=data.defaultFolder; await put(SETTINGS_STORE,{key:"defaultFolder",value:data.defaultFolder}); } await Promise.all(state.files.map(function(f){return put(FILE_STORE,f)}).concat(state.folders.map(function(f){return put(FOLDER_STORE,f)}))); state.deviceLibraryReady=true; return true; }catch(err){ state.deviceLibraryReady=false; if(showErrors&&err.name!=="NotFoundError") toast(err.message||"Could not read device library","error"); return false; } }
async function writeDeviceManifest(showErrors){ if(!state.deviceLibraryHandle) return false; var ok=await ensureDevicePermission(true,false); if(!ok) return false; try{ var payload={version:1,updatedAt:new Date().toISOString(),profile:state.profile,defaultFolder:state.currentFolder==="all-folders"?"root":state.currentFolder,folders:state.folders,files:state.files}; var fileHandle=await state.deviceLibraryHandle.getFileHandle(DEVICE_MANIFEST,{create:true}); var writable=await fileHandle.createWritable(); await writable.write(JSON.stringify(payload,null,2)); await writable.close(); state.deviceLibraryReady=true; if(showErrors) renderDeviceLibraryPanel(); return true; }catch(err){ state.deviceLibraryReady=false; if(showErrors) toast(err.message||"Could not write device library","error"); return false; } }
async function copyUploadedFileToDeviceLibrary(file,record){ if(!state.deviceLibraryHandle) return; var ok=await ensureDevicePermission(true,false); if(!ok) return; try{ var dir=await state.deviceLibraryHandle.getDirectoryHandle(DEVICE_FILES_DIR,{create:true}); var safeName=record.id+"-"+safeDeviceFileName(file.name); var fileHandle=await dir.getFileHandle(safeName,{create:true}); var writable=await fileHandle.createWritable(); await writable.write(file); await writable.close(); record.localDeviceFile=DEVICE_FILES_DIR+"/"+safeName; }catch(err){ toast("Uploaded to Telegram, but the device copy was not saved","error"); } }
async function getDeviceFileObjectUrl(f){ if(!f.localDeviceFile||!state.deviceLibraryHandle) return null; var ok=await ensureDevicePermission(false,false); if(!ok) return null; try{ var parts=f.localDeviceFile.split("/"); var dir=await state.deviceLibraryHandle.getDirectoryHandle(parts[0]); var fileHandle=await dir.getFileHandle(parts.slice(1).join("/")); var file=await fileHandle.getFile(); var url=URL.createObjectURL(file); state.uploadUrls.set(f.id,url); return url; }catch(e){ return null; } }
function renderDeviceLibraryPanel(){ var grid=$(".settings-grid"); if(!grid) return; var existing=$("#deviceLibraryPanel"); if(!existing){ grid.insertAdjacentHTML("afterend",'<section id="deviceLibraryPanel" class="device-library-panel"></section>'); existing=$("#deviceLibraryPanel"); } var supported=deviceLibrarySupported(); var connected=!!state.deviceLibraryHandle; var status=!supported?"Not supported in this browser":connected?(state.deviceLibraryReady?"Connected and writable":"Connected; sync may need permission"):"No device folder connected"; existing.innerHTML='<div><strong>Device Library</strong><p>'+escapeHtml(status)+(connected?' • '+escapeHtml(state.deviceLibraryName):'')+'</p></div><div class="device-library-actions"><button type="button" class="secondary compact" data-action="connect-device-library">'+(connected?"Change Folder":"Connect Folder")+'</button><button type="button" class="secondary compact" data-action="sync-device-library" '+(!supported?"disabled":"")+'>Sync Now</button>'+(connected?'<button type="button" class="danger compact" data-action="disconnect-device-library">Disconnect</button>':"")+'</div>'; }
function renderOnboardingDeviceStatus(){ var status=$("#onboardingDeviceStatus"), btn=$("#onboardingDeviceButton"); if(!status||!btn) return; var supported=deviceLibrarySupported(), connected=!!state.deviceLibraryHandle; status.textContent=!supported?"Folder protection needs a Chromium browser.":connected?"Connected to "+state.deviceLibraryName+". Your tiny recovery file will stay there.":"No folder connected yet."; btn.textContent=connected?"Change Folder":"Connect Folder"; btn.disabled=!supported; }
function safeDeviceFileName(name){ return String(name||"file").replace(/[<>:"/\\|?*\x00-\x1F]/g,"_").slice(0,120); }
function detectCategory(file){ var t=file.type||"", n=file.name.toLowerCase(); if(t.indexOf("image/")===0) return "images"; if(t.indexOf("video/")===0) return "videos"; if(t.indexOf("audio/")===0) return "audio"; if(/\.(zip|rar|7z|tar|gz)$/i.test(n)) return "archives"; return "documents"; }
function iconClass(c){ return c==="images"?"image":c==="videos"?"video":c==="audio"?"audio":c==="archives"?"archive":"doc"; }
function sorter(s){ return function(a,b){ if(s==="name-asc") return a.name.localeCompare(b.name); if(s==="name-desc") return b.name.localeCompare(a.name); if(s==="size-asc") return a.size-b.size; if(s==="size-desc") return b.size-a.size; if(s==="type-asc") return (a.type||a.category).localeCompare(b.type||b.category); if(s==="date-asc") return new Date(a.uploadDate)-new Date(b.uploadDate); return new Date(b.uploadDate)-new Date(a.uploadDate); }; }
function isRecent(d){ return Date.now()-new Date(d).getTime()<7*24*60*60*1000; }
function folderPath(id){ var f=state.folders.find(function(x){return x.id===id}); if(!f) return "TeleDrive"; var names=[], cur=f, guard=0; while(cur&&guard<12){ names.unshift(cur.name); cur=state.folders.find(function(x){return x.id===cur.parentId}); guard++; } return names.join(" / "); }
function formatBytes(bytes){ if(!bytes) return "0 B"; var u=["B","KB","MB","GB"], i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),u.length-1); return (bytes/Math.pow(1024,i)).toFixed(i?1:0)+" "+u[i]; }
function formatDate(d){ return new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",year:"numeric"}).format(new Date(d)); }
function capitalize(v){ return v.charAt(0).toUpperCase()+v.slice(1); }
function initials(name){ var parts=String(name||"").trim().split(/\s+/).filter(Boolean); return (parts[0]&&parts[1]?parts[0][0]+parts[1][0]:String(name||"VK").slice(0,2)).toUpperCase(); }
function escapeHtml(v){ return String(v||"").replace(/[&<>'"]/g,function(c){ return {"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]; }); }
function toast(msg,type){ var n=document.createElement("div"); n.className="toast "+(type||"info"); n.textContent=msg; $("#toastStack").append(n); setTimeout(function(){n.remove()},4200); }
function initRevealObserver(){ var obs=new IntersectionObserver(function(entries){ entries.forEach(function(e){ if(e.isIntersecting) e.target.classList.add("visible"); }); },{threshold:.14}); $$(".reveal").forEach(function(el){ obs.observe(el); }); }
function initParticles(){ var c=$("#particleCanvas"), ctx=c.getContext("2d"), w=0,h=0,parts=[]; function resize(){ w=c.width=Math.floor(innerWidth*devicePixelRatio); h=c.height=Math.floor(innerHeight*devicePixelRatio); c.style.width=innerWidth+"px"; c.style.height=innerHeight+"px"; var count=Math.min(88,Math.max(34,Math.floor(innerWidth/18))); parts=Array.from({length:count},function(){ return {x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.28*devicePixelRatio,vy:(Math.random()-.5)*.28*devicePixelRatio,r:(Math.random()*1.8+.7)*devicePixelRatio,a:Math.random()*.36+.12}; }); } function frame(){ ctx.clearRect(0,0,w,h); if(state.animations){ parts.forEach(function(p){ p.x+=p.vx; p.y+=p.vy; if(p.x<0||p.x>w) p.vx*=-1; if(p.y<0||p.y>h) p.vy*=-1; ctx.beginPath(); ctx.fillStyle="rgba(69,184,231,"+p.a+")"; ctx.arc(p.x,p.y,p.r,0,Math.PI*2); ctx.fill(); }); } requestAnimationFrame(frame); } addEventListener("resize",resize); resize(); frame(); }
